version: "3.0"

services:
  config-server:
    image: steeltoeoss/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes: 
      - ../config:/config
    environment:
      #SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/Pivotal-Field-Engineering/funny-quotes-config
      #SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: /config
      SPRING_PROFILES_ACTIVE: native

  eureka:
    image: steeltoeoss/eurekaserver
    environment: 
      eureka_server_enableSelfPreservation: "false" # we want things to get kicked out of the registry when app is shut down
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 8084:15672
      - 15672:15672
      - 5672:5672
      
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    
  omnidb: 
    image: taivokasper/omnidb
    ports:
      - 8085:8080
      - 25482:25482

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: DotnetAccelerator
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /database
    volumes:
      - postgresql:/database

  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 8084:15672
      - 15672:15672
      - 5672:5672
  
  mysql:
     image: mysql:5.7
     volumes:
       - ./data/mysql:/var/lib/mysql
     ports:
       - "3306:3306"
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - mysql
    environment:
     - PMA_HOST=mysql
     - PMA_USER=root
     - PMA_PASSWORD=
    restart: always
    ports:
     - 8083:80
    volumes:
     - /sessions

  spring-boot-admin:
    image: steeltoeoss/spring-boot-admin
    ports: 
      - 8088:8080 
      
volumes:
  postgresql: